spring:
  application:
    name: log-service
  profiles:
    active: dev

  # 数据库配置 - 日志模块专用数据库
  datasource:
    url: jdbc:mysql://localhost:3306/log_module?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 19990626ZYX

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# 服务端口 - 日志服务
server:
  port: 8085

# 日志配置
logging:
  level:
    com.example.log: debug
    org.springframework.data.jpa: debug
  file:
    name: logs/log-service.log