spring:
  # 数据源配置 - 生产环境
  datasource:
    url: jdbc:mysql://prod-db:3306/multi_module_prod?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${DB_USERNAME:prod_user}
    password: ${DB_PASSWORD:prod_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis配置 - 生产环境
  redis:
    host: ${REDIS_HOST:prod-redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:prod_redis_pass}
    database: 0

# 服务端口
server:
  port: ${SERVER_PORT:8080}

# 日志配置 - 生产环境
logging:
  level:
    root: error
    com.example: warn
  file:
    name: logs/app-prod.log
    max-size: 100MB
    max-history: 30

# JWT配置 - 生产环境使用环境变量
jwt:
  secret: ${JWT_SECRET:myProductionSecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400}

# 文件上传配置 - 生产环境
file:
  upload:
    path: ${FILE_UPLOAD_PATH:/data/uploads/}
    max-size: ${FILE_MAX_SIZE:50MB}
    allowed-types: ${FILE_ALLOWED_TYPES:jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx}