spring:
  # 数据源配置 - 开发环境
  datasource:
    url: ${server.config.database.url:jdbc:mysql://${server.config.database.host}:${server.config.database.port}/multi_module_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8}
    username: ${server.config.database.username}
    password: ${server.config.database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # Redis配置 - 开发环境
  redis:
    host: ${server.config.redis.host}
    port: ${server.config.redis.port}
    password: ${server.config.redis.password}
    database: ${server.config.redis.database}


# 日志配置 - 开发环境
logging:
  level:
    root: info
    com.example: debug
  file:
    name: logs/app-dev.log