spring:
  profiles:
    active: dev
  application:
    name: springboot-multi-module
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin123
        allow: 127.0.0.1

  # Redis配置
  redis:
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# JWT配置
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400

# 文件上传配置
file:
  upload:
    path: /tmp/uploads/
    max-size: 10MB
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx

# 日志配置
logging:
  level:
    com.example: debug
    org.springframework.security: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"

# Swagger配置
swagger:
  enabled: true
  title: SpringBoot多模块项目API文档
  description: SpringBoot多模块项目接口文档
  version: 1.0.0
  contact:
    name: 开发团队
    email: dev@example.com

# 服务器配置 - 统一管理所有IP和端口
server:
  config:
    # 数据库配置
    database:
      host: localhost
      port: 3306
      username: root
      password: 19990626ZYX
    
    # Redis配置
    redis:
      host: localhost
      port: 6379
      password: ""
      database: 0
    
    # 微服务配置
    services:
      host: localhost
      auth:
        port: 8081
      user:
        port: 8082
      file:
        port: 8083
      admin:
        port: 8084
      log:
        port: 8085
    
    # 网关配置
    gateway:
      port: 8080
    
    # 安全配置
    security:
      allowed-ip: 127.0.0.1
      allowed-ips: 127.0.0.1,localhost
