spring:
  # 数据源配置 - 开发环境
  datasource:
    url: jdbc:mysql://localhost:3306/multi_module_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 19990626ZYX
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # Redis配置 - 开发环境
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0


# 日志配置 - 开发环境
logging:
  level:
    root: info
    com.example: debug
  file:
    name: logs/app-dev.log