# 共享配置文件 - 所有模块都可以引用
# 使用方法：在各模块的application.yml中使用spring.config.import导入此文件

# 服务器配置 - 统一管理所有IP和端口
server:
  config:
    # 数据库配置
    database:
      host: localhost
      port: 3306
      username: root
      password: 19990626ZYX
    
    # Redis配置
    redis:
      host: localhost
      port: 6379
      password: ""
      database: 0
    
    # 微服务配置
    services:
      host: localhost
      auth:
        port: 8081
      user:
        port: 8082
      file:
        port: 8083
      admin:
        port: 8084
      log:
        port: 8085
    
    # 网关配置
    gateway:
      port: 8080
    
    # 安全配置
    security:
      allowed-ip: 127.0.0.1
      allowed-ips: 127.0.0.1,localhost

# Spring Security 统一配置
app:
  security:
    enabled: true
    # 无需认证的路径
    permit-all-paths:
      - "/swagger-ui/**"
      - "/v3/api-docs/**"
      - "/swagger-resources/**"
      - "/webjars/**"
      - "/druid/**"
      - "/actuator/**"
      - "/auth/login"
      - "/auth/register"
      - "/user/check-username"
      - "/user/check-email"
      - "/common/id/**"
      - "/common/security/public"
    # 统一用户账号配置
    users:
      - username: admin
        password: admin123
        role: ADMIN
      - username: user
        password: user123
        role: USER
      - username: developer
        password: dev123
        role: DEVELOPER

# Spring Security 基础配置
spring:
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN
