spring:
  application:
    name: file-service
  profiles:
    active: dev
  
  # 导入共享配置
  config:
    import:
      - "classpath:shared-config.yml"

# 服务端口 - 文件服务（使用统一配置，提供默认值）
server:
  port: ${server.config.services.file.port}

# 日志配置
logging:
  level:
    com.example.file: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/file-service.log

# 文件上传配置
file:
  upload:
    path: /tmp/uploads/
    max-size: 10MB
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx
