spring:
  application:
    name: file-service
  profiles:
    active: dev
  
  # 导入共享配置
  config:
    import:
      - "classpath:shared-config.yml"
  
  # 文件上传大小限制配置
  servlet:
    multipart:
      max-file-size: 100MB      # 单个文件最大大小
      max-request-size: 100MB   # 整个请求最大大小
      enabled: true             # 启用文件上传

# 服务端口 - 文件服务（使用统一配置，提供默认值）
server:
  port: ${server.config.services.file.port}

# 日志配置
logging:
  level:
    com.example.file: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/file-service.log

# 文件上传配置
file:
  upload:
    path: /tmp/uploads/
    max-size: 100MB  # 增加文件大小限制
    allowed-types: "*"  # 支持所有文件类型
    check-file-type: false  # 关闭文件类型检查
