spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  
  # 导入共享配置
  config:
    import:
      - "classpath:shared-config.yml"
  
  # Redis配置 - 使用统一配置，提供默认值
  redis:
    host: ${server.config.redis.host}
    port: ${server.config.redis.port}
    password: ${server.config.redis.password}
    database: ${server.config.redis.database}
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  
  # Spring Cloud Gateway配置 - 使用统一配置，提供默认值
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://${server.config.services.host}:${server.config.services.auth.port}
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://${server.config.services.host}:${server.config.services.user.port}
          predicates:
            - Path=/user/**
        - id: file-service
          uri: http://${server.config.services.host}:${server.config.services.file.port}
          predicates:
            - Path=/file/**
        - id: admin-service
          uri: http://${server.config.services.host}:${server.config.services.admin.port}
          predicates:
            - Path=/admin/**
        - id: log-service
          uri: http://${server.config.services.host}:${server.config.services.log.port}
          predicates:
            - Path=/log/**

# JWT配置
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400

# 服务端口 - 网关入口（使用统一配置，提供默认值）
server:
  port: ${server.config.gateway.port}

# 日志配置
logging:
  level:
    com.example.gateway: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/gateway-service.log
